language: ruby
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.2
before_install: gem install bundler -v 1.10.5
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - lotus db migrate
addons:
  postgresql: "9.2"
  code_climate:
    repo_token:
      secure: 3114381b79144c596a639491c0ee58f038123920d2b2c89f53bb0e1e949b98b0
env:
  - SPEEDUP_RB_DATABASE_URL="postgres://postgres@localhost/travis_ci_test"
